# Generated by Django 5.0.6 on 2024-06-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogFunc", "0002_alter_post_options_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ("title",),
            },
        ),
    ]
