# Generated by Django 5.0.6 on 2024-06-24 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogFunc", "0005_remove_comment_posts_post_posts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="posts",
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="blogFunc.category",
            ),
            preserve_default=False,
        ),
    ]
