# Generated by Django 5.0.6 on 2024-06-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogFunc", "0007_alter_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("draft", "Draft")],
                default="active",
                max_length=10,
            ),
        ),
    ]
